### ISSUE TITLE
Instamine Deepslate not included

### ISSUE THREAD

**Issue by Carmassi** [Crec0/JankAddons#3]
Hi! I've downloaded the 1.18.1-1.0.4 release and it said it had the instamine deepslate rule but in game it doesn't show up in the commands nor in the source files, and (just a minor error) in the mod menu it's saying the mod is in 1.0.3 even though i downloaded the 1.0.4 version.

**Comment by Crec0** [comment]
- The commands go through carpet mod, so, to enable the rule you need to run the command `/carpet instamineDeepslate true` to enable it. 
- to use `/carpet` commands you need cheats enabled OR op 2 or above (if on server)
- Ah yes forgot to bump version in fabric.mod.json. :p

**Comment by Carmassi** [comment]
Strangely enough, when i tried downloading the github version 1.0.4 it didn't work but i downloaded the same version from Curseforge and it worked, the command appeard in game and worked. Thank you for the attention and this addition. 😀
